!function(t){var e={};function n(o){if(e[o])return e[o].exports;var r=e[o]={i:o,l:!1,exports:{}};return t[o].call(r.exports,r,r.exports,n),r.l=!0,r.exports}n.m=t,n.c=e,n.d=function(t,e,o){n.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:o})},n.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},n.t=function(t,e){if(1&e&&(t=n(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var o=Object.create(null);if(n.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var r in t)n.d(o,r,function(e){return t[e]}.bind(null,r));return o},n.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(e,"a",e),e},n.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},n.p="",n(n.s="./src/ts/background.ts")}({"./src/ts/background.ts":
/*!******************************!*\
  !*** ./src/ts/background.ts ***!
  \******************************/
/*! no static exports found */function(t,e,n){"use strict";var o=this&&this.__awaiter||function(t,e,n,o){return new(n||(n=Promise))((function(r,i){function u(t){try{c(o.next(t))}catch(t){i(t)}}function a(t){try{c(o.throw(t))}catch(t){i(t)}}function c(t){var e;t.done?r(t.value):(e=t.value,e instanceof n?e:new n((function(t){t(e)}))).then(u,a)}c((o=o.apply(t,e||[])).next())}))};Object.defineProperty(e,"__esModule",{value:!0});const r=n(/*! ./global */"./src/ts/global.ts");function i(){return o(this,void 0,void 0,(function*(){const t=yield r.getStorage(r.StorageFlag.TOKEN);t?yield function(t){return o(this,void 0,void 0,(function*(){confirm(`You have already set a GitHub token (${t}), do you want to remove it?`)&&(yield r.removeStorage(r.StorageFlag.TOKEN),alert("You have removed GitHub token successfully."))}))}(t):confirm("Do you want to setup a GitHub token to access the private repos?")&&(yield function(){return o(this,void 0,void 0,(function*(){var t=prompt("Please enter your GitHub token: \n(You can visit https://github.com/settings/token to to get token.)");null!==t&&((t=t.trim())?(yield r.setStorage(r.StorageFlag.TOKEN,t),alert("Done! Your GitHub token has been set successfully, reload this page to see changes.")):alert("Oops! You have entered an empty token."))}))}())}))}chrome.browserAction.onClicked.addListener(t=>o(void 0,void 0,void 0,(function*(){yield i()}))),e.onActionClicked=i},"./src/ts/global.ts":
/*!**************************!*\
  !*** ./src/ts/global.ts ***!
  \**************************/
/*! no static exports found */function(t,e,n){"use strict";var o,r=this&&this.__awaiter||function(t,e,n,o){return new(n||(n=Promise))((function(r,i){function u(t){try{c(o.next(t))}catch(t){i(t)}}function a(t){try{c(o.throw(t))}catch(t){i(t)}}function c(t){var e;t.done?r(t.value):(e=t.value,e instanceof n?e:new n((function(t){t(e)}))).then(u,a)}c((o=o.apply(t,e||[])).next())}))};Object.defineProperty(e,"__esModule",{value:!0});class i{}e.Global=i,i.token="",i.pinned=!1,i.page=1,i.isHovering=!1,i.FEEDBACK_URL="https://github.com/Aoi-hosizora/GithubEventsExt/issues",function(t){t.TOKEN="ah-token",t.PINNED="ah-pinned",t.WIDTH="ah-width"}(o=e.StorageFlag||(e.StorageFlag={}));const u=chrome.storage.sync||chrome.storage.local;e.setStorage=function(t,e){return r(this,void 0,void 0,(function*(){return new Promise((n,o)=>{const r={[t.toString()]:e};u.set(r,()=>n())})}))},e.getStorage=function(t){return r(this,void 0,void 0,(function*(){return new Promise((e,n)=>{u.get(t.toString(),n=>{var o=n[t.toString()];e(o)})})}))},e.removeStorage=function(t){return r(this,void 0,void 0,(function*(){return new Promise((e,n)=>{u.remove(t.toString(),()=>e())})}))},e.readStorageToGlobal=function(){return r(this,void 0,void 0,(function*(){return new Promise((t,e)=>{u.get(e=>{i.token=e[o.TOKEN.toString()],i.pinned=e[o.PINNED.toString()],i.width=e[o.WIDTH.toString()],t()})})}))}}});
//# sourceMappingURL=background.js.map